# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 19:49
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]