# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 19:56
from __future__ import unicode_literals

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_customer_pwd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='pwd',
            new_name='password',
        ),
    ]