# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-28 19:59
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20170829_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]